### ISSUE TITLE
Link to Pixelblaze

### ISSUE THREAD

**Issue by beroe** [simap/flower_chandelier#1]
Hi. 
The current link to https://www.bhencke.com/pixelblaze is a relative link, so gets pre-pended with the github info and fails... 
I'd love to see a bit more about how the LEDs are connected to the mount. Can't quite visualize it. 
Very nice project..!

**Comment by simap** [comment]
@beroe , thanks for the heads-up!
The LEDs are looped around the mount, and rest on the edge, facing outward. The strips have sticky back, which helps, but I also tack them down with some heat glue.

**Comment by simap** [comment]
@beroe 
![mounting leds](https://user-images.githubusercontent.com/1427631/33222307-1ac4da44-d10b-11e7-8d70-6c6412e5508d.jpg)
